baseurl = "/"
title = "Benjamin Wong"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disqusShortname = "yourdiscussshortname"

[params]
    author = "Benjamin Wong"
    description = "Ben's Personal Blogsite"
    keywords = "blog, epidemiologist,  global health, public health, datascience, r, stata, python, gis"
    info = "Epidemiologist"
    avatarurl = "images/avatar.jpg"
    footercontent = "..."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/benkcwong/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/benkcwong/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/benckcwong/"
[[params.social]]
    name = "Research Gate"
    icon = "fab fa-researchgate"
    weight = 4
    url = "https://www.researchgate.net/profile/Benjamin_Wong5/"
[[params.social]]
    name = "Google Scholar"
    icon = "fab fa-google-plus-square"
    weight = 5
    url = "https://scholar.google.ca/citations?user=87cmlcIAAAAJ&hl=en"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = ""

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Benjamin Wong"
        info = "Epidemiologist"
        description = "Ben's Personal Blogsite"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Say Hi!"
        weight = 5
        url = "/contact/"


    [languages.pl]
        languagename = "Francais"
        title = ""

        [languages.pl.params]
            author = "Benjamin Wong"
            description = "le Site de Ben"
            keywords = "blog, epidemiologiste, sante mondiale, sante publique, science des donnees, r, stata, python, gis"
            info = "Epidemiologiste"

        [languages.pl.menu]

            [[languages.pl.menu.main]]
            name = "De Moi"
            weight = 1
            url = "/pl/about/"

            [[languages.pl.menu.main]]
            name = "Blog"
            weight = 2
            url = "/pl/posts/"

            [[languages.pl.menu.main]]
            name = "Projets"  
            weight = 3
            url = "/pl/projects/"

            [[languages.pl.menu.main]]
            name = "Dis Bonjour"
            weight = 5
            url = "/pl/contact/"
